---
- name: Disable UFW
  ansible.builtin.include_tasks: disable-ufw.yml

- name: Install Packages
  ansible.builtin.include_tasks: install-packages.yml

- name: Configure K3s agent
  ansible.builtin.include_tasks: configure-k3s.yml

- name: Configure Cluster
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  loop:
    - configure-cluster.yml
    - fetch-kube-config.yml
  when: "'K3S_SERVER' in group_names"
