---
- name: Disable UFW
  ansible.builtin.include_tasks: disable-ufw.yml

- name: Install Containerd
  ansible.builtin.include_tasks: install-containerd.yml

- name: Install K3s
  ansible.builtin.include_tasks: install-k3s.yml

- name: Configure K3s server
  ansible.builtin.include_tasks:
    file: "{{ item }}"
  loop:
    - configure-k3s.yml
    - capture-k3s-token.yml
    - install-longhorn.yml
  when: "'K3S_SERVER' in group_names"

- name: Configure K3s agent
  ansible.builtin.include_tasks: configure-k3s.yml
  when: "'K3S_AGENT' in group_names"
