---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvc
  namespace: grafana
spec:
  storageClassName: longhorn
  volumeName: grafana-pv
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
