---
- name: Installing Packages
  ansible.builtin.apt:
    pkg:
      - qemu-guest-agent
    state: present
    update-cache: true

- name: Setting Hostname
  ansible.builtin.hostname:
    name: "{{ inventory_hostname }}"

- name: Set SSH Authorized Keys
  ansible.posix.authorized_key:
    state: present
    user: "{{ ansible_user }}"
    key: "{{ item }}"
  loop:
    - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIES3MWtrYdJGdRLvp6oKl3SWHYGGcR725ZaZmu2+kcWx
    # - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIDMJvrddIRBp6UWEim5D6jCPegLHwh+doe7c744GA7v/
    # - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAICjX0kDFSxu41RfqJOytpKePct4PrWpwvKkjbEMvhbTV
- name: Create SSH Private Key
  ansible.builtin.copy:
    dest: ~/.ssh/id_ed25519
    content: "{{ ssh_private_key }}"
    mode: "0600"
  when: create_ssh_private_key
