apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-conf
  labels:
    name: prometheus-conf
  namespace: {{ .Values.appNamespace }}
data:
  prometheus.yml: |-
    global:
      scrape_interval: 5s
      evaluation_interval: 5s
    scrape_configs:
      - job_name: 'kube-state-metrics'
        static_configs:
          - targets: ['monitoring-kube-state-metrics.monitoring.svc.cluster.local:8080']
          