apiVersion: v1
kind: Service
metadata:
  name: prometheus
  namespace: {{ .Values.appNamespace }}
  annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port:   '9090'
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: http-prometheus
  selector:
    app: prometheus
  sessionAffinity: None
  type: LoadBalancer